import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import customersRouter from "./customers";
import conversationsRouter from "./conversations";
import messagesRouter from "./messages";
import tagsRouter from "./tags";
import quickRepliesRouter from "./quick-replies";
import analyticsRouter from "./analytics";
import settingsRouter from "./settings";
import insightsRouter from "./insights";
import campaignsRouter from "./campaigns";
import rolePermissionsRouter from "./role-permissions";
import chatReasonCategoriesRouter from "./chat-reason-categories";
import chatReasonsRouter from "./chat-reasons";
import notReadyReasonsRouter from "./not-ready-reasons";
import meRouter from "./me";
import webhooksRouter from "./webhooks";
import uploadsRouter from "./uploads";
import customerAiRouter from "./customer-ai";
import userPermissionsRouter from "./user-permissions";

const router: IRouter = Router();

router.use(healthRouter);
router.use(webhooksRouter);
router.use(authRouter);
router.use(userPermissionsRouter);
router.use(usersRouter);
router.use(customersRouter);
router.use(customerAiRouter);
router.use(conversationsRouter);
router.use(messagesRouter);
router.use(uploadsRouter);
router.use(tagsRouter);
router.use(quickRepliesRouter);
router.use(analyticsRouter);
router.use(settingsRouter);
router.use(insightsRouter);
router.use(campaignsRouter);
router.use(rolePermissionsRouter);
router.use(chatReasonCategoriesRouter);
router.use(chatReasonsRouter);
router.use(notReadyReasonsRouter);
router.use(meRouter);

export default router;
